-- ============================================================
-- Seed: Corporate Gifting Category Taxonomy
-- Adds 22 Main Categories (level 1), 24 Sub Categories (level 2),
-- 24 Sub Sub Categories (level 3) themed around corporate gifting.
-- Requires migration 002_categories_extended_fields.sql to be applied first.
-- Safe to re-run: uses unique slugs, will fail on duplicate rather than double-insert.
-- ============================================================

-- ── LEVEL 1: MAIN CATEGORIES ──────────────────────────────────
INSERT INTO categories
  (name, slug, description, parent_id, icon, status, display_order, is_featured, level,
   desktop_menu_status, desktop_menu_order, desktop_home_show, desktop_home_design, desktop_home_order,
   mobile_topbar_status, mobile_topbar_order, mobile_sidebar_order,
   mobile_home_show, mobile_home_design, mobile_home_format, mobile_home_order,
   meta_title, meta_keywords, meta_description)
VALUES
('Corporate Gift Sets','corporate-gift-sets','Curated gift sets designed for bulk corporate orders and employee gifting.',0,'fas fa-gift','active',1,1,1,'show',1,'yes','design1',1,'show',1,1,'yes','design1','4',1,'Corporate Gift Sets | Bulk Corporate Gifting','corporate gift sets, bulk gifting, corporate gifts','Shop premium corporate gift sets for employees, clients and events. Customizable and bulk-order friendly.'),
('Drinkware & Mugs','drinkware-mugs','Printed mugs, bottles and tumblers for corporate branding and gifting.',0,'fas fa-mug-hot','active',2,1,1,'show',2,'yes','design1',2,'show',2,2,'yes','design1','4',2,'Drinkware & Mugs | Corporate Gifting','corporate mugs, branded bottles, drinkware gifts','Customized mugs, bottles and tumblers perfect for corporate gifting and branding.'),
('Bags & Backpacks','bags-backpacks','Laptop bags, totes and backpacks for corporate and promotional use.',0,'fas fa-briefcase','active',3,1,1,'show',3,'yes','design1',3,'show',3,3,'yes','design1','4',3,'Bags & Backpacks | Corporate Gifting','corporate bags, branded backpacks, tote bags','Durable and stylish bags and backpacks, customizable for corporate gifting programs.'),
('Tech & Gadgets','tech-gadgets','Power banks, speakers and gadgets for modern corporate gifting.',0,'fas fa-microchip','active',4,1,1,'show',4,'yes','design1',4,'show',4,4,'yes','design1','4',4,'Tech & Gadgets | Corporate Gifting','tech gifts, gadget gifting, corporate electronics','Trending tech gadgets like power banks, speakers and chargers, ideal for employee and client gifts.'),
('Office & Desk Accessories','office-desk-accessories','Desk organizers, notepads and accessories for office gifting.',0,'fas fa-desktop','active',5,1,1,'show',5,'yes','design1',5,'show',5,5,'yes','design1','4',5,'Office & Desk Accessories | Corporate Gifting','desk accessories, office gifts, desk organizers','Practical office and desk accessories that make thoughtful corporate gifts.'),
('Apparel & T-Shirts','apparel-tshirts','Branded t-shirts, polos and jackets for corporate uniforms and gifting.',0,'fas fa-tshirt','active',6,1,1,'show',6,'yes','design1',6,'show',6,6,'yes','design1','4',6,'Apparel & T-Shirts | Corporate Gifting','corporate t-shirts, branded apparel, polo shirts','Custom-branded apparel including t-shirts, polos and jackets for teams and events.'),
('Pens & Writing Instruments','pens-writing-instruments','Metal pens, roller balls and pen sets for executive gifting.',0,'fas fa-pen','active',7,1,1,'show',7,'yes','design1',7,'show',7,7,'yes','design1','4',7,'Pens & Writing Instruments | Corporate Gifting','corporate pens, executive pen sets, branded pens','Elegant writing instruments and pen sets suited for executive corporate gifting.'),
('Diaries & Notebooks','diaries-notebooks','A5 diaries, planners and notebooks for corporate gifting.',0,'fas fa-book','active',8,1,1,'show',8,'yes','design1',8,'show',8,8,'yes','design1','4',8,'Diaries & Notebooks | Corporate Gifting','corporate diaries, branded notebooks, planners','Premium diaries and notebooks customizable with company branding.'),
('Awards & Trophies','awards-trophies','Crystal awards, plaques and trophies for corporate recognition.',0,'fas fa-trophy','active',9,1,1,'show',9,'yes','design1',9,'show',9,9,'yes','design1','4',9,'Awards & Trophies | Corporate Gifting','corporate awards, crystal trophies, recognition plaques','Recognition awards, trophies and plaques for employee and achievement recognition.'),
('Festive & Diwali Gifts','festive-diwali-gifts','Diwali hampers and festive gift boxes for corporate distribution.',0,'fas fa-star','active',10,1,1,'show',10,'yes','design1',10,'show',10,10,'yes','design1','4',10,'Festive & Diwali Gifts | Corporate Gifting','diwali gifts, festive hampers, corporate diwali gifting','Festive gift hampers and Diwali gift boxes designed for bulk corporate distribution.'),
('Eco-Friendly Gifts','eco-friendly-gifts','Bamboo, jute and sustainable gifting products.',0,'fas fa-leaf','active',11,1,1,'show',11,'yes','design1',11,'show',11,11,'yes','design1','4',11,'Eco-Friendly Gifts | Corporate Gifting','eco friendly gifts, sustainable corporate gifts, bamboo products','Sustainable and eco-conscious gifts made from bamboo, jute and recycled materials.'),
('Keychains & Accessories','keychains-accessories','Metal and leather keychains for promotional gifting.',0,'fas fa-key','active',12,0,1,'show',12,'no','',12,'show',12,12,'no','','4',12,'Keychains & Accessories | Corporate Gifting','corporate keychains, branded accessories','Compact promotional keychains and accessories perfect for giveaways.'),
('Wallets & Card Holders','wallets-card-holders','Leather wallets and card holders for premium corporate gifting.',0,'fas fa-wallet','active',13,0,1,'show',13,'no','',13,'show',13,13,'no','','4',13,'Wallets & Card Holders | Corporate Gifting','corporate wallets, card holders, leather gifting','Premium leather wallets and card holders for executive gifting.'),
('Home & Kitchen Gifts','home-kitchen-gifts','Kitchen and home decor items for corporate hamper gifting.',0,'fas fa-home','active',14,0,1,'show',14,'no','',14,'show',14,14,'no','','4',14,'Home & Kitchen Gifts | Corporate Gifting','home gifts, kitchen gifts, corporate hampers','Home and kitchen products curated for corporate hampers and festive gifting.'),
('Personal Care Gift Sets','personal-care-gift-sets','Grooming and wellness gift sets for employee wellbeing programs.',0,'fas fa-spa','active',15,0,1,'show',15,'no','',15,'show',15,15,'no','','4',15,'Personal Care Gift Sets | Corporate Gifting','personal care gifts, wellness gift sets, grooming kits','Grooming and wellness gift sets ideal for employee wellbeing and appreciation gifting.'),
('Corporate Hampers','corporate-hampers','Combo gift hampers for clients, employees and special occasions.',0,'fas fa-box-open','active',16,1,1,'show',16,'yes','design2',16,'show',16,16,'yes','design2','6',16,'Corporate Hampers | Corporate Gifting','corporate hampers, gift combos, client hampers','Ready-to-gift combo hampers curated for clients, employees and festive occasions.'),
('Customized Merchandise','customized-merchandise','Fully branded merchandise for corporate promotions.',0,'fas fa-tags','active',17,0,1,'show',17,'no','',17,'show',17,17,'no','','4',17,'Customized Merchandise | Corporate Gifting','custom merchandise, branded products, promo items','Fully customizable branded merchandise for corporate promotions and events.'),
('Employee Welcome Kits','employee-welcome-kits','Onboarding kits for new employee welcome gifting.',0,'fas fa-user-plus','active',18,0,1,'show',18,'no','',18,'show',18,18,'no','','4',18,'Employee Welcome Kits | Corporate Gifting','welcome kits, onboarding gifts, new joinee gifts','Thoughtfully curated welcome kits to onboard new employees in style.'),
('Client Appreciation Gifts','client-appreciation-gifts','Premium gifts to thank and retain valued clients.',0,'fas fa-handshake','active',19,1,1,'show',19,'yes','design1',19,'show',19,19,'yes','design1','4',19,'Client Appreciation Gifts | Corporate Gifting','client gifts, appreciation gifts, business gifting','Premium appreciation gifts designed to strengthen client relationships.'),
('Promotional Products','promotional-products','Budget-friendly branded giveaways for events and exhibitions.',0,'fas fa-bullhorn','active',20,0,1,'show',20,'no','',20,'show',20,20,'no','','4',20,'Promotional Products | Corporate Gifting','promotional products, event giveaways, branded giveaways','Cost-effective branded giveaways ideal for exhibitions, trade shows and events.'),
('Umbrellas & Rainwear','umbrellas-rainwear','Branded umbrellas and rain gear for corporate gifting.',0,'fas fa-umbrella','active',21,0,1,'show',21,'no','',21,'show',21,21,'no','','4',21,'Umbrellas & Rainwear | Corporate Gifting','corporate umbrellas, branded rainwear','Durable branded umbrellas and rainwear for seasonal corporate gifting.'),
('Travel Accessories','travel-accessories','Luggage tags, travel kits and organizers for corporate gifting.',0,'fas fa-suitcase-rolling','active',22,0,1,'show',22,'no','',22,'show',22,22,'no','','4',22,'Travel Accessories | Corporate Gifting','travel gifts, luggage accessories, travel kits','Handy travel accessories and organizers that make practical corporate gifts.');

-- ── LEVEL 2: SUB CATEGORIES ───────────────────────────────────
INSERT INTO categories
  (name, slug, description, parent_id, icon, status, display_order, is_featured, level,
   desktop_menu_status, desktop_menu_order, desktop_menu_tag,
   mobile_topbar_status, mobile_topbar_order, mobile_sidebar_order,
   meta_title, meta_keywords, meta_description)
VALUES
('Ceramic Mugs','ceramic-mugs','Printable ceramic mugs for daily use and gifting.',41,'','active',1,0,2,'show',1,'','show',1,1,'Ceramic Mugs | Corporate Gifting','ceramic mugs, printed mugs','Classic ceramic mugs available for bulk printing and corporate branding.'),
('Steel Water Bottles','steel-water-bottles','Insulated steel bottles for corporate gifting.',41,'','active',2,1,2,'show',2,'New','show',2,2,'Steel Water Bottles | Corporate Gifting','steel bottles, insulated bottles','Durable steel water bottles, customizable with company logos.'),
('Travel Tumblers','travel-tumblers','Portable tumblers ideal for on-the-go corporate gifting.',41,'','active',3,0,2,'show',3,'','show',3,3,'Travel Tumblers | Corporate Gifting','travel tumblers, corporate tumblers','Sleek travel tumblers perfect for daily commutes and branding.'),
('Laptop Bags','laptop-bags','Padded laptop bags for corporate gifting and uniforms.',42,'','active',1,1,2,'show',1,'Popular','show',1,1,'Laptop Bags | Corporate Gifting','laptop bags, corporate bags','Protective and stylish laptop bags for employees and clients.'),
('Tote Bags','tote-bags','Reusable tote bags for eco-conscious corporate gifting.',42,'','active',2,0,2,'show',2,'','show',2,2,'Tote Bags | Corporate Gifting','tote bags, canvas bags','Reusable tote bags ideal for events, conferences and giveaways.'),
('Duffel Bags','duffel-bags','Spacious duffel bags for travel and sports gifting.',42,'','active',3,0,2,'show',3,'','show',3,3,'Duffel Bags | Corporate Gifting','duffel bags, travel bags','Roomy duffel bags suited for corporate sports and travel gifting programs.'),
('Power Banks','power-banks','Portable chargers for corporate tech gifting.',43,'','active',1,1,2,'show',1,'Trending','show',1,1,'Power Banks | Corporate Gifting','power banks, portable chargers','Reliable power banks in multiple capacities for corporate tech gifting.'),
('Bluetooth Speakers','bluetooth-speakers','Wireless speakers for premium corporate gifting.',43,'','active',2,1,2,'show',2,'Hot','show',2,2,'Bluetooth Speakers | Corporate Gifting','bluetooth speakers, wireless speakers','Compact and portable Bluetooth speakers for gifting and events.'),
('USB Flash Drives','usb-flash-drives','Branded pen drives for corporate promotions.',43,'','active',3,0,2,'show',3,'','show',3,3,'USB Flash Drives | Corporate Gifting','usb drives, pen drives','Custom-branded USB flash drives available in multiple storage sizes.'),
('Wireless Chargers','wireless-chargers','Qi wireless chargers for modern corporate gifting.',43,'','active',4,0,2,'show',4,'','show',4,4,'Wireless Chargers | Corporate Gifting','wireless chargers, qi chargers','Fast wireless charging pads, a popular pick for tech-forward gifting.'),
('Desk Organizers','desk-organizers','Multi-purpose organizers for tidy corporate desks.',44,'','active',1,0,2,'show',1,'','show',1,1,'Desk Organizers | Corporate Gifting','desk organizers, office organizers','Functional desk organizers to declutter workspaces, great as office gifts.'),
('Sticky Notes & Notepads','sticky-notes-notepads','Branded notepads and sticky notes for office gifting.',44,'','active',2,0,2,'show',2,'','show',2,2,'Sticky Notes & Notepads | Corporate Gifting','sticky notes, notepads','Everyday notepads and sticky notes customizable with branding.'),
('Desk Clocks','desk-clocks','Elegant desk clocks for executive office gifting.',44,'','active',3,0,2,'show',3,'','show',3,3,'Desk Clocks | Corporate Gifting','desk clocks, office clocks','Stylish desk clocks that double as thoughtful office gifts.'),
('Polo T-Shirts','polo-tshirts','Corporate polo t-shirts for uniforms and gifting.',45,'','active',1,1,2,'show',1,'Popular','show',1,1,'Polo T-Shirts | Corporate Gifting','polo t-shirts, corporate uniforms','Comfortable polo t-shirts customizable for company uniforms and gifting.'),
('Round Neck T-Shirts','round-neck-tshirts','Casual round neck t-shirts for event gifting.',45,'','active',2,0,2,'show',2,'','show',2,2,'Round Neck T-Shirts | Corporate Gifting','round neck t-shirts, event t-shirts','Everyday round neck t-shirts perfect for team events and promotions.'),
('Corporate Jackets','corporate-jackets','Branded jackets for winter corporate gifting.',45,'','active',3,0,2,'show',3,'','show',3,3,'Corporate Jackets | Corporate Gifting','corporate jackets, branded jackets','Premium jackets branded with company logos for winter gifting.'),
('Metal Pens','metal-pens','Engraved metal pens for executive gifting.',46,'','active',1,1,2,'show',1,'Premium','show',1,1,'Metal Pens | Corporate Gifting','metal pens, engraved pens','Sleek metal pens available for laser engraving and corporate branding.'),
('Executive Pen Sets','executive-pen-sets','Boxed pen sets for premium client gifting.',46,'','active',2,0,2,'show',2,'','show',2,2,'Executive Pen Sets | Corporate Gifting','pen sets, executive gifts','Elegant boxed pen sets designed for premium executive gifting.'),
('A5 Diaries','a5-diaries','Compact A5 diaries for corporate gifting.',47,'','active',1,1,2,'show',1,'Bestseller','show',1,1,'A5 Diaries | Corporate Gifting','a5 diaries, corporate diaries','Compact A5-sized diaries, customizable with branding and inserts.'),
('Planner Notebooks','planner-notebooks','Dated planners for productivity-focused gifting.',47,'','active',2,0,2,'show',2,'','show',2,2,'Planner Notebooks | Corporate Gifting','planner notebooks, dated planners','Dated planner notebooks that help recipients stay organized year-round.'),
('Crystal Awards','crystal-awards','Premium crystal awards for employee recognition.',48,'','active',1,1,2,'show',1,'Premium','show',1,1,'Crystal Awards | Corporate Gifting','crystal awards, recognition trophies','Elegant crystal awards for milestone and achievement recognition.'),
('Wooden Plaques','wooden-plaques','Engraved wooden plaques for corporate recognition.',48,'','active',2,0,2,'show',2,'','show',2,2,'Wooden Plaques | Corporate Gifting','wooden plaques, engraved plaques','Classic engraved wooden plaques suited for corporate recognition ceremonies.'),
('Diwali Gift Hampers','diwali-gift-hampers','Curated Diwali hampers for corporate distribution.',49,'','active',1,1,2,'show',1,'Festive','show',1,1,'Diwali Gift Hampers | Corporate Gifting','diwali hampers, festive gift boxes','Ready-to-gift Diwali hampers curated for bulk corporate distribution.'),
('Bamboo Eco Products','bamboo-eco-products','Sustainable bamboo products for eco-friendly gifting.',50,'','active',1,0,2,'show',1,'Eco','show',1,1,'Bamboo Eco Products | Corporate Gifting','bamboo products, eco friendly gifts','Sustainable bamboo-based products for environmentally conscious gifting.');

-- ── LEVEL 3: SUB SUB CATEGORIES ───────────────────────────────
INSERT INTO categories
  (name, slug, description, parent_id, icon, status, display_order, is_featured, level,
   desktop_menu_status, desktop_menu_order, desktop_menu_tag,
   mobile_topbar_status, mobile_topbar_order, mobile_sidebar_order,
   meta_title, meta_keywords, meta_description)
VALUES
('Printed Ceramic Mugs','printed-ceramic-mugs','Full-color printed ceramic mugs.',62,'','active',1,0,3,'show',1,'','show',1,1,'Printed Ceramic Mugs','printed mugs','Full-color printed ceramic mugs for personalized corporate gifting.'),
('Magic Color-Changing Mugs','color-changing-mugs','Heat-sensitive color-changing mugs.',62,'','active',2,1,3,'show',2,'New','show',2,2,'Magic Color-Changing Mugs','magic mugs, color changing mugs','Fun heat-sensitive mugs that reveal designs when filled with hot liquid.'),
('Insulated Steel Bottles','insulated-steel-bottles','Double-wall insulated steel bottles.',63,'','active',1,0,3,'show',1,'','show',1,1,'Insulated Steel Bottles','insulated bottles','Double-wall insulated bottles that keep drinks hot or cold for hours.'),
('Sipper Bottles','sipper-bottles','Lightweight sipper bottles for daily use.',63,'','active',2,0,3,'show',2,'','show',2,2,'Sipper Bottles','sipper bottles','Lightweight sipper bottles ideal for gym and daily office use.'),
('15.6-Inch Laptop Bags','laptop-bags-156-inch','Bags fitted for 15.6-inch laptops.',65,'','active',1,0,3,'show',1,'','show',1,1,'15.6-Inch Laptop Bags','laptop bags 15 inch','Laptop bags precisely fitted for 15.6-inch laptops and accessories.'),
('Anti-Theft Laptop Bags','anti-theft-laptop-bags','Secure anti-theft laptop backpacks.',65,'','active',2,1,3,'show',2,'Premium','show',2,2,'Anti-Theft Laptop Bags','anti theft bags','Secure anti-theft laptop backpacks with hidden zip compartments.'),
('Canvas Tote Bags','canvas-tote-bags','Sturdy canvas tote bags.',66,'','active',1,0,3,'show',1,'','show',1,1,'Canvas Tote Bags','canvas totes','Sturdy canvas tote bags, a reusable favorite for event giveaways.'),
('Jute Tote Bags','jute-tote-bags','Eco-friendly jute tote bags.',66,'','active',2,0,3,'show',2,'Eco','show',2,2,'Jute Tote Bags','jute totes','Eco-friendly jute tote bags suited for sustainable gifting programs.'),
('10000mAh Power Banks','power-bank-10000mah','Compact 10000mAh power banks.',68,'','active',1,0,3,'show',1,'','show',1,1,'10000mAh Power Banks','10000mah power bank','Compact 10000mAh power banks ideal for everyday carry.'),
('20000mAh Power Banks','power-bank-20000mah','High-capacity 20000mAh power banks.',68,'','active',2,1,3,'show',2,'Popular','show',2,2,'20000mAh Power Banks','20000mah power bank','High-capacity 20000mAh power banks for extended device charging.'),
('Mini Bluetooth Speakers','mini-bluetooth-speakers','Pocket-sized Bluetooth speakers.',69,'','active',1,0,3,'show',1,'','show',1,1,'Mini Bluetooth Speakers','mini speakers','Pocket-sized Bluetooth speakers, easy to carry and gift.'),
('Portable Party Speakers','portable-party-speakers','Louder speakers for events and parties.',69,'','active',2,0,3,'show',2,'','show',2,2,'Portable Party Speakers','party speakers','Higher-output portable speakers suited for events and celebrations.'),
('16GB Pen Drives','usb-pendrive-16gb','16GB capacity pen drives.',70,'','active',1,0,3,'show',1,'','show',1,1,'16GB Pen Drives','16gb pendrive','Reliable 16GB pen drives for everyday data storage gifting.'),
('32GB Pen Drives','usb-pendrive-32gb','32GB capacity pen drives.',70,'','active',2,0,3,'show',2,'','show',2,2,'32GB Pen Drives','32gb pendrive','Higher-capacity 32GB pen drives for corporate data gifting.'),
('Wooden Desk Organizers','wooden-desk-organizers','Handcrafted wooden desk organizers.',72,'','active',1,0,3,'show',1,'','show',1,1,'Wooden Desk Organizers','wooden organizers','Handcrafted wooden desk organizers that add warmth to any workspace.'),
('Multi-Compartment Organizers','multi-compartment-organizers','Organizers with multiple compartments.',72,'','active',2,0,3,'show',2,'','show',2,2,'Multi-Compartment Organizers','multi compartment organizers','Organizers with multiple compartments to sort stationery and gadgets.'),
('Cotton Polo T-Shirts','cotton-polo-tshirts','100% cotton polo t-shirts.',75,'','active',1,0,3,'show',1,'','show',1,1,'Cotton Polo T-Shirts','cotton polo','Breathable 100% cotton polo t-shirts for daily wear and uniforms.'),
('Dry-Fit Polo T-Shirts','dryfit-polo-tshirts','Moisture-wicking dry-fit polo t-shirts.',75,'','active',2,1,3,'show',2,'Sport','show',2,2,'Dry-Fit Polo T-Shirts','dry fit polo','Moisture-wicking dry-fit polo t-shirts suited for sports events.'),
('Engraved Metal Pens','engraved-metal-pens','Laser-engraved metal pens.',78,'','active',1,0,3,'show',1,'','show',1,1,'Engraved Metal Pens','engraved pens','Laser-engraved metal pens personalized with names or logos.'),
('Twist-Action Metal Pens','twist-action-metal-pens','Smooth twist-action metal pens.',78,'','active',2,0,3,'show',2,'','show',2,2,'Twist-Action Metal Pens','twist pens','Smooth twist-action metal pens with a comfortable executive grip.'),
('Leather A5 Diaries','leather-a5-diaries','Genuine leather-bound A5 diaries.',80,'','active',1,1,3,'show',1,'Premium','show',1,1,'Leather A5 Diaries','leather diaries','Genuine leather-bound A5 diaries for a premium gifting feel.'),
('PU A5 Diaries','pu-a5-diaries','Affordable PU leather A5 diaries.',80,'','active',2,0,3,'show',2,'','show',2,2,'PU A5 Diaries','pu diaries','Affordable PU leather A5 diaries, ideal for bulk corporate orders.'),
('Star-Shaped Crystal Awards','star-crystal-awards','Star-shaped crystal award pieces.',82,'','active',1,0,3,'show',1,'','show',1,1,'Star-Shaped Crystal Awards','star crystal award','Star-shaped crystal awards for standout achievement recognition.'),
('Rectangular Crystal Awards','rectangular-crystal-awards','Classic rectangular crystal award blocks.',82,'','active',2,0,3,'show',2,'','show',2,2,'Rectangular Crystal Awards','rectangular crystal award','Classic rectangular crystal award blocks for formal recognition events.');
