import React from 'react';

const TermsOfUse = () => {
  return (
    <div className="container-fluid bg-light py-3">
      <div className="container bg-white shadow-sm p-3 p-md-4 rounded-4" style={{ maxWidth: '1100px' }}>
        
        <section className="text-secondary" style={{ fontSize: '0.95rem', lineHeight: '1.6' }}>
          <p className="mb-2 text-dark">
            Disclaimer: In case of any discrepancy or difference, the English version will take precedence over the translation
          </p>
          <p className="mb-2">
            In case of any discrepancy or difference, the English version will take precedence over the translation
          </p>
          <p className="mb-2">
            This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2">
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform")
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2">
            The Platform is owned by Printmont Corporation Pvt. Ltd., a company incorporated under the Companies Act, 1956 with its registered office at 3398, Bagichi Acchi ji, Bara Hindu Rao, Near Filmistan Cinema, New Delhi, India - 110006 and its branch offices at ... (hereinafter referred to as "Printmont").
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2">
            Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Printmont Corporation Pvt. Ltd. and these terms and conditions including the policies constitute Your binding obligations, with Printmont.
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2">
            As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Printmont reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Printmont's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2">
            For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Printmont allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Printmont Corporation Pvt. Ltd.
          </p>
          
          <hr className="my-3 border-secondary border-opacity-25" />
          
          <p className="my-2 text-uppercase">
            ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Printmont Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
          </p>
        </section>

      </div>
    </div>
  );
};

export default TermsOfUse;
