-- ============================================================
-- Migration 003: Home Sections Setup
-- Creates the home_sections table to manage ordering, type, and status
-- of all components on desktop and mobile homepages.
-- ============================================================

CREATE TABLE IF NOT EXISTS `home_sections` (
  `id`                    int(11)       NOT NULL AUTO_INCREMENT,
  `page_target`           enum('desktop','mobile') NOT NULL,
  `section_type`          varchar(50)   NOT NULL COMMENT 'slider | banner | product_carousel | category_mosaic | compact_grid | mobile_list | featured_grid | brand_directory | bulk_widget | gift_finder',
  `section_key`           varchar(80)   NOT NULL,
  `label`                 varchar(120)  NOT NULL,
  `columns_per_row`       tinyint(1)    NOT NULL DEFAULT 1,
  `is_slider`             tinyint(1)    NOT NULL DEFAULT 0,
  `api_action`            varchar(80)   DEFAULT NULL,
  `product_limit`         int(11)       DEFAULT 10,
  `badge_text`            varchar(50)   DEFAULT NULL,
  `background_image_url`  varchar(255)  DEFAULT NULL,
  `display_order`         int(11)       NOT NULL DEFAULT 0,
  `status`                enum('active','inactive') NOT NULL DEFAULT 'active',
  `created_at`            timestamp     NOT NULL DEFAULT current_timestamp(),
  `updated_at`            timestamp     NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_target_key` (`page_target`, `section_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Seed DESKTOP Homepage layout
INSERT IGNORE INTO `home_sections` 
  (`page_target`, `section_type`, `section_key`, `label`, `columns_per_row`, `is_slider`, `api_action`, `product_limit`, `badge_text`, `display_order`, `status`) 
VALUES
  ('desktop', 'slider', 'home_hero', 'Hero Slider (Full Width)', 1, 1, NULL, NULL, NULL, 1, 'active'),
  ('desktop', 'banner', 'home_above_fold', 'Above Fold Banners (4 Columns)', 4, 0, NULL, NULL, NULL, 2, 'active'),
  ('desktop', 'slider', 'home_mid_section_1', 'Mid Section Carousel (3 Columns)', 3, 1, NULL, NULL, NULL, 3, 'active'),
  ('desktop', 'slider', 'home_mid_section_2', 'Mid Section Carousel (4 Columns)', 4, 1, NULL, NULL, NULL, 4, 'active'),
  ('desktop', 'product_carousel', 'desktop_bestsellers', 'Our Bestsellers', 1, 0, 'bestseller', 12, 'Customizable', 5, 'active'),
  ('desktop', 'banner', 'home_mid_section_3', 'Mid Section Banner (Single)', 1, 0, NULL, NULL, NULL, 6, 'active'),
  ('desktop', 'gift_finder', 'gift_finder', 'Gift Finder Widget', 1, 0, NULL, NULL, NULL, 7, 'active'),
  ('desktop', 'product_carousel', 'desktop_top_selection', 'Top Selection', 1, 0, 'top_selection', 12, 'Customizable', 8, 'active'),
  ('desktop', 'banner', 'home_banner_api6', 'Desktop Banners API 6 (3 Columns)', 3, 0, NULL, NULL, NULL, 9, 'active'),
  ('desktop', 'product_carousel', 'desktop_discount_for_you', 'Discount For You', 1, 0, 'discount_for_you', 12, 'Customizable', 10, 'active'),
  ('desktop', 'banner', 'home_banner_api7', 'Responsive Banners API 7', 3, 0, NULL, NULL, NULL, 11, 'active'),
  ('desktop', 'product_carousel', 'desktop_top_rated', 'Top Rated', 1, 0, 'top_rated', 12, 'Customizable', 12, 'active'),
  ('desktop', 'banner', 'home_banner_api8', 'Responsive Banners API 8', 3, 0, NULL, NULL, NULL, 13, 'active'),
  ('desktop', 'product_carousel', 'desktop_top_deal', 'Top Deals and Categories', 1, 0, 'top_deal', 12, 'Customizable', 14, 'active'),
  ('desktop', 'banner', 'home_banner_api9', 'Responsive Banners API 9', 3, 0, NULL, NULL, NULL, 15, 'active'),
  ('desktop', 'product_carousel', 'desktop_womens_outfits', "Women's Outfits", 1, 0, 'top_selection', 12, NULL, 16, 'active'),
  ('desktop', 'category_mosaic', 'desktop_mosaic_grouped_1', 'Category Grouped Mosaic 1', 1, 0, 'grouped_categories', NULL, NULL, 17, 'active'),
  ('desktop', 'category_mosaic', 'desktop_mosaic_grouped_2', 'Category Grouped Mosaic 2 (Reverse)', 1, 0, 'grouped_categories', NULL, NULL, 18, 'active'),
  ('desktop', 'banner', 'home_banner_api11', 'Desktop Banners API 11 (3 Columns)', 3, 0, NULL, NULL, NULL, 19, 'active'),
  ('desktop', 'category_mosaic', 'desktop_mosaic_grouped_3', 'Category Grouped Mosaic 3', 1, 0, 'grouped_categories', NULL, NULL, 20, 'active'),
  ('desktop', 'banner', 'home_banner_api14', 'Responsive Banners API 14', 3, 0, NULL, NULL, NULL, 21, 'active'),
  ('desktop', 'featured_grid', 'featured_grid_1', 'Featured Product Grid 1', 1, 0, NULL, NULL, NULL, 22, 'active'),
  ('desktop', 'banner', 'home_banner_api13', 'Desktop Banners API 13 (3 Columns)', 3, 0, NULL, NULL, NULL, 23, 'active'),
  ('desktop', 'featured_grid', 'featured_grid_2', 'Featured Product Grid 2', 1, 0, NULL, NULL, NULL, 24, 'active'),
  ('desktop', 'banner', 'home_banner_static_single_1', 'Static Single Banner 1', 1, 0, NULL, NULL, NULL, 25, 'active'),
  ('desktop', 'category_mosaic', 'desktop_mosaic_flat_mens', "Men's Category Mosaic (Flat)", 1, 0, 'top_rated', NULL, NULL, 26, 'active'),
  ('desktop', 'banner', 'home_banner_static_single_2', 'Static Single Banner 2', 1, 0, NULL, NULL, NULL, 27, 'active'),
  ('desktop', 'category_mosaic', 'desktop_mosaic_flat_womens', "Women's Category Mosaic (Flat)", 1, 0, 'top_deal', NULL, NULL, 28, 'active'),
  ('desktop', 'product_carousel', 'desktop_recently_viewed', 'Recently Viewed Products', 1, 0, 'discount_for_you', 12, NULL, 29, 'active'),
  ('desktop', 'brand_directory', 'brand_directory', 'Brand Directory Section', 1, 0, NULL, NULL, NULL, 30, 'active'),
  ('desktop', 'bulk_widget', 'bulk_widget', 'Bulk Order Widget', 1, 0, NULL, NULL, NULL, 31, 'active');

-- Seed MOBILE Homepage layout
INSERT IGNORE INTO `home_sections` 
  (`page_target`, `section_type`, `section_key`, `label`, `columns_per_row`, `is_slider`, `api_action`, `product_limit`, `badge_text`, `background_image_url`, `display_order`, `status`) 
VALUES
  ('mobile', 'slider', 'home_hero', 'Hero Slider (Full Width)', 1, 1, NULL, NULL, NULL, NULL, 1, 'active'),
  ('mobile', 'slider', 'mobile_hero_slider', 'Mobile Hero Slider', 1, 1, NULL, NULL, NULL, NULL, 2, 'active'),
  ('mobile', 'banner', 'home_above_fold', 'Above Fold Banners (2 Columns)', 2, 0, NULL, NULL, NULL, NULL, 3, 'active'),
  ('mobile', 'product_carousel', 'mobile_recently_viewed', 'Recently Viewed', 1, 0, 'top_rated', 10, NULL, NULL, 4, 'active'),
  ('mobile', 'banner', 'home_mid_section_3', 'Mid Section Banner (Single)', 1, 0, NULL, NULL, NULL, NULL, 5, 'active'),
  ('mobile', 'compact_grid', 'mobile_end_of_season_sale', 'End of Season Sale Grid', 1, 0, 'top_selection', 6, NULL, NULL, 6, 'active'),
  ('mobile', 'category_mosaic', 'mobile_tableware_dinnerware', 'Tableware & Dinnerware Mosaic', 1, 0, NULL, NULL, NULL, NULL, 7, 'active'),
  ('mobile', 'product_carousel', 'mobile_hour_flash_sale', 'Only for 1 Hour Carousel', 1, 0, 'special_offer', 10, NULL, './bg/flashsale.png', 8, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_1', 'Grid Banners 2 Col 1', 2, 0, NULL, NULL, NULL, NULL, 9, 'active'),
  ('mobile', 'featured_grid', 'mobile_section_nine', 'Section Nine Products', 1, 0, NULL, NULL, NULL, NULL, 10, 'active'),
  ('mobile', 'category_mosaic', 'mobile_grouped_mosaic_api', 'Dynamic Grouped Category Mosaic', 1, 0, 'grouped_categories', NULL, NULL, NULL, 11, 'active'),
  ('mobile', 'category_mosaic', 'mobile_womens_fashion_mosaic', "Women's Fashion Mosaic", 1, 0, NULL, NULL, NULL, NULL, 12, 'active'),
  ('mobile', 'product_carousel', 'mobile_top_selection', 'Top Selection Carousel', 1, 0, 'top_selection', 10, 'Customizable', NULL, 13, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_2', 'Grid Banners 2 Col 2', 2, 0, NULL, NULL, NULL, NULL, 14, 'active'),
  ('mobile', 'product_carousel', 'mobile_discount_for_you', 'Discount For You Carousel', 1, 0, 'discount_for_you', 10, 'Customizable', NULL, 15, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_3', 'Grid Banners 2 Col 3', 2, 0, NULL, NULL, NULL, NULL, 16, 'active'),
  ('mobile', 'product_carousel', 'mobile_top_deals_cat_1', 'Top Deals on Categories Carousel', 1, 0, 'top_deal', 10, 'Customizable', NULL, 17, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_4', 'Grid Banners 2 Col 4', 2, 0, NULL, NULL, NULL, NULL, 18, 'active'),
  ('mobile', 'product_carousel', 'mobile_womens_carousel', "Women's Carousel", 1, 0, 'top_deal', 10, NULL, NULL, 19, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_4col_1', 'Grid Banners 4 Col 1', 4, 0, NULL, NULL, NULL, NULL, 20, 'active'),
  ('mobile', 'banner', 'mobile_responsive_banner_set', 'Responsive Banner Set', 1, 0, NULL, NULL, NULL, NULL, 21, 'active'),
  ('mobile', 'category_mosaic', 'mobile_earbuds_headphones', 'EarBuds & Headphones Mosaic', 1, 0, NULL, NULL, NULL, NULL, 22, 'active'),
  ('mobile', 'product_carousel', 'mobile_top_deals_cat_2', 'Top Deals on Categories Carousel 2', 1, 0, 'top_deal', 10, 'Customizable', NULL, 23, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_discount_for_you', 'Discount For You List', 1, 0, 'discount_for_you', 10, NULL, NULL, 24, 'active'),
  ('mobile', 'category_mosaic', 'mobile_home_decor', 'Home Decor Mosaic', 1, 0, NULL, NULL, NULL, NULL, 25, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_top_selection', 'Top Selection List', 1, 0, 'top_selection', 10, NULL, NULL, 26, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_5', 'Grid Banners 2 Col 5', 2, 0, NULL, NULL, NULL, NULL, 27, 'active'),
  ('mobile', 'category_mosaic', 'mobile_mobiles_mosaic', 'Mobiles Mosaic', 1, 0, NULL, NULL, NULL, NULL, 28, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_top_rated', 'Top Rated List', 1, 0, 'top_rated', 10, NULL, NULL, 29, 'active'),
  ('mobile', 'compact_grid', 'mobile_great_choices', 'Great Choices Grid', 1, 0, 'top_deal', 6, NULL, NULL, 30, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_top_selection_2', 'Top Selection List 2', 1, 0, 'top_selection', 10, NULL, NULL, 31, 'active'),
  ('mobile', 'featured_grid', 'mobile_featured_grid_1', 'Featured Product Grid 1', 1, 0, NULL, NULL, NULL, NULL, 32, 'active'),
  ('mobile', 'category_mosaic', 'mobile_mens_fashion_mosaic', "Men's Fashion Mosaic", 1, 0, NULL, NULL, NULL, NULL, 33, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_6', 'Grid Banners 2 Col 6', 2, 0, NULL, NULL, NULL, NULL, 34, 'active'),
  ('mobile', 'featured_grid', 'mobile_featured_grid_2', 'Featured Product Grid 2', 1, 0, NULL, NULL, NULL, NULL, 35, 'active'),
  ('mobile', 'banner', 'mobile_static_responsive_banner_1', 'Static Responsive Banner 1', 1, 0, NULL, NULL, NULL, NULL, 36, 'active'),
  ('mobile', 'featured_grid', 'mobile_featured_grid_3', 'Featured Product Grid 3', 1, 0, NULL, NULL, NULL, NULL, 37, 'active'),
  ('mobile', 'category_mosaic', 'mobile_new_fashion_mosaic', 'New Fashion Mosaic', 1, 0, NULL, NULL, NULL, NULL, 38, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_top_deal', 'Top Deal List', 1, 0, 'top_deal', 10, NULL, NULL, 39, 'active'),
  ('mobile', 'product_carousel', 'mobile_health_wellness', 'Best of Health & Wellness Carousel', 1, 0, 'discount_for_you', 10, 'Customizable', NULL, 40, 'active'),
  ('mobile', 'product_carousel', 'mobile_electronics', 'Electronics Carousel', 1, 0, 'top_rated', 10, 'Customizable', NULL, 41, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_7', 'Grid Banners 2 Col 7', 2, 0, NULL, NULL, NULL, NULL, 42, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_top_rated_2', 'Top Rated List 2', 1, 0, 'top_rated', 10, NULL, NULL, 43, 'active'),
  ('mobile', 'product_carousel', 'mobile_home_usage', 'Home Usage Carousel', 1, 0, 'top_selection', 10, 'Customizable', NULL, 44, 'active'),
  ('mobile', 'category_mosaic', 'mobile_best_for_health', 'Best for Health Mosaic', 1, 0, NULL, NULL, NULL, NULL, 45, 'active'),
  ('mobile', 'mobile_list', 'mobile_list_discount_for_you_2', 'Discount For You List 2', 1, 0, 'discount_for_you', 10, NULL, NULL, 46, 'active'),
  ('mobile', 'product_carousel', 'mobile_recently_viewed_2', 'Recently Viewed Carousel 2', 1, 0, 'top_selection', 10, NULL, NULL, 47, 'active'),
  ('mobile', 'banner', 'mobile_static_responsive_banner_2', 'Static Responsive Banner 2', 1, 0, NULL, NULL, NULL, NULL, 48, 'active'),
  ('mobile', 'banner', 'mobile_banner_grid_2col_8', 'Grid Banners 2 Col 8', 2, 0, NULL, NULL, NULL, NULL, 49, 'active'),
  ('mobile', 'category_mosaic', 'mobile_flat_womens', "Women's Flat Category Mosaic", 1, 0, 'top_deal', NULL, NULL, NULL, 50, 'active'),
  ('mobile', 'brand_directory', 'brand_directory', 'Brand Directory Section', 1, 0, NULL, NULL, NULL, NULL, 51, 'active');
