import React from "react";
import { Nav } from "react-bootstrap";
import { Routes, Route, Link, useLocation, Navigate } from "react-router-dom";
import "./Policy.css";
import PageNotFound from "../pageNotFound/PageNotFound";
import { 
  FaFileContract, 
  FaUserShield, 
  FaTruck, 
  FaUndoAlt, 
  FaCheckCircle, 
  FaClock, 
  FaBoxOpen, 
  FaLock, 
  FaCookie, 
  FaDatabase 
} from "react-icons/fa";

const PolicyPage = () => {
  const location = useLocation();

  const tabs = [
    { path: "/policy/terms", label: "Terms & Conditions" },
    { path: "/policy/privacy", label: "Privacy Policy" },
    { path: "/policy/shipping", label: "Shipping Policy" },
    { path: "/policy/refund", label: "Return & Refund Policy" },
  ];

  return (
    <div className="policy-page container-fluid mx-0 px-0 py-4 py-lg-5">
      <h2 className="fw-bold text-center mb-4 text-dark" style={{ letterSpacing: "-0.5px" }}>Company Policies</h2>

      {/* Tabs */}
      <Nav className="justify-content-start justify-content-md-center mb-4 border-0 flex-nowrap overflow-auto px-3" style={{ whiteSpace: 'nowrap', scrollbarWidth: 'none' }}>
        {tabs.map((tab) => (
          <Nav.Item key={tab.path}>
            <Nav.Link
              as={Link}
              to={tab.path}
              className={`policy-tab px-4 py-2.5 fw-bold ${
                location.pathname === tab.path ? "active-tab text-white" : "text-secondary"
              } text-decoration-none`}
            >
              {tab.label}
            </Nav.Link>
          </Nav.Item>
        ))}
      </Nav>

      {/* Policy Content */}
      <div className="policy-content mx-auto p-4 p-md-5 bg-white" style={{ maxWidth: '950px' }}>
        <Routes>
          <Route path="/" element={<Navigate to="terms" replace />} />
          <Route path="terms" element={<Terms />} />
          <Route path="privacy" element={<Privacy />} />
          <Route path="shipping" element={<Shipping />} />
          <Route path="refund" element={<Refund />} />
          <Route path="*" element={<PageNotFound />} />
        </Routes>
      </div>
    </div>
  );
};

/* ---------- INDIVIDUAL POLICY COMPONENTS ---------- */

const Terms = () => (
  <section className="policy-section-animation" style={{ lineHeight: '1.8', fontSize: '0.95rem', color: '#4a5568' }}>
    <div className="d-flex align-items-center gap-3 mb-4">
      <div className="rounded-circle bg-primary bg-opacity-10 p-3 text-primary d-flex align-items-center justify-content-center" style={{ width: '56px', height: '56px' }}>
        <FaFileContract size={24} />
      </div>
      <div>
        <h4 className="fw-bold mb-0 text-dark">Terms & Conditions</h4>
        <p className="text-muted small mb-0">Last updated: July 2026</p>
      </div>
    </div>
    
    <div className="alert alert-warning border-0 rounded-3 mb-4 shadow-sm d-flex align-items-start gap-3" role="alert" style={{ background: '#fff9db' }}>
      <span className="fs-5 mt-0.5">⚠️</span>
      <div className="small text-dark-emphasis">
        <strong>Disclaimer:</strong> In case of any discrepancy or difference, the English version will take precedence over any translation.
      </div>
    </div>
    
    <div className="row g-4 mb-4">
      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">1. Electronic Record</h6>
          <p className="small text-muted mb-0">
            This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder. This record is generated by a computer system and does not require physical or digital signatures.
          </p>
        </div>
      </div>
      
      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">2. Rule of Publishing</h6>
          <p className="small text-muted mb-0">
            Published in accordance with Rule 3 (1) of the IT (Intermediaries guidelines) Rules, 2011 requiring publishing rules, regulations, privacy policy and Terms of Use for access or usage of domain.
          </p>
        </div>
      </div>

      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">3. Ownership</h6>
          <p className="small text-muted mb-0">
            The Platform is owned by <strong>Printmont Corporation Pvt. Ltd.</strong>, incorporated under the Companies Act, 1956, with registered office in New Delhi, India.
          </p>
        </div>
      </div>

      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">4. Binding Obligations</h6>
          <p className="small text-muted mb-0">
            By transacting on or using the Platform, you contract with Printmont Corporation Pvt. Ltd., and these terms constitute your binding obligations.
          </p>
        </div>
      </div>

      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">5. Minor Transactions</h6>
          <p className="small text-muted mb-0">
            Minors under 18 must transact via legal guardians. Printmont reserves the right to terminate membership if it is discovered the user is under 18 years of age.
          </p>
        </div>
      </div>

      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">6. Definitions</h6>
          <p className="small text-muted mb-0">
            "You" or "User" refers to any natural or legal person registered or surfing the site. "We", "Us", "Our" refers to Printmont Corporation Pvt. Ltd.
          </p>
        </div>
      </div>
    </div>

    <div className="p-3 rounded-3 text-dark bg-primary bg-opacity-10 border border-primary border-opacity-10">
      <p className="mb-0 fw-semibold text-primary" style={{ fontSize: '0.88rem', lineHeight: '1.6' }}>
        ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS. Please read carefully before transacting.
      </p>
    </div>
  </section>
);

const Privacy = () => (
  <section className="policy-section-animation" style={{ lineHeight: '1.8', fontSize: '0.95rem', color: '#4a5568' }}>
    <div className="d-flex align-items-center gap-3 mb-4">
      <div className="rounded-circle bg-success bg-opacity-10 p-3 text-success d-flex align-items-center justify-content-center" style={{ width: '56px', height: '56px' }}>
        <FaUserShield size={24} />
      </div>
      <div>
        <h4 className="fw-bold mb-0 text-dark">Privacy Policy</h4>
        <p className="text-muted small mb-0">Last updated: July 2026</p>
      </div>
    </div>
    
    <p className="text-secondary mb-4">
      Your privacy is critical to our values. We gather personal information solely to elevate your experience and offer personalized printing solutions.
    </p>

    <div className="row g-4 mb-4">
      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaCookie className="text-success mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Cookie Policy</h6>
          <p className="small text-muted mb-0">We use cookies to personalize product configurations and analyze traffic flows.</p>
        </div>
      </div>

      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaDatabase className="text-success mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Data Deletion</h6>
          <p className="small text-muted mb-0">Users hold absolute rights to request complete removal of account and design history.</p>
        </div>
      </div>

      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaLock className="text-success mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Data Security</h6>
          <p className="small text-muted mb-0">All transaction and product details are guarded using industry-grade SSL encryption.</p>
        </div>
      </div>
    </div>

    <h6 className="fw-bold text-dark mt-4 mb-3">Key Commitments:</h6>
    <ul className="list-unstyled d-flex flex-column gap-2 mb-0">
      <li className="d-flex align-items-start gap-2">
        <FaCheckCircle className="text-success mt-1" size={14} />
        <span>No sharing of design files or personal details with unauthorized partners.</span>
      </li>
      <li className="d-flex align-items-start gap-2">
        <FaCheckCircle className="text-success mt-1" size={14} />
        <span>Strict zero-spam notification and promotional email configuration policies.</span>
      </li>
      <li className="d-flex align-items-start gap-2">
        <FaCheckCircle className="text-success mt-1" size={14} />
        <span>Transparent logging of system configuration logs for order dispatch efficiency.</span>
      </li>
    </ul>
  </section>
);

const Shipping = () => (
  <section className="policy-section-animation" style={{ lineHeight: '1.8', fontSize: '0.95rem', color: '#4a5568' }}>
    <div className="d-flex align-items-center gap-3 mb-4">
      <div className="rounded-circle bg-info bg-opacity-10 p-3 text-info d-flex align-items-center justify-content-center" style={{ width: '56px', height: '56px' }}>
        <FaTruck size={24} />
      </div>
      <div>
        <h4 className="fw-bold mb-0 text-dark">Shipping Policy</h4>
        <p className="text-muted small mb-0">Last updated: July 2026</p>
      </div>
    </div>
    
    <p className="text-secondary mb-4">
      We strive to dispatch your custom orders with the highest quality checks. Review our shipping processes below.
    </p>

    <div className="row g-4 mb-4">
      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaClock className="text-info mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Processing</h6>
          <p className="small text-muted mb-0">Orders are checked and processed within 2-3 business days after setup confirmation.</p>
        </div>
      </div>

      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaBoxOpen className="text-info mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Packaging</h6>
          <p className="small text-muted mb-0">Triple-layered bubble wrapping for print canvases to avoid physical transit damages.</p>
        </div>
      </div>

      <div className="col-12 col-md-4">
        <div className="card h-100 border-0 p-3 rounded-3 text-center bg-light">
          <FaTruck className="text-info mb-3 mx-auto" size={28} />
          <h6 className="fw-bold text-dark">Tracking</h6>
          <p className="small text-muted mb-0">Live tracking link dispatched via SMS and email immediately upon carrier handover.</p>
        </div>
      </div>
    </div>

    <div className="alert alert-info border-0 rounded-3 mb-0" role="alert" style={{ background: '#e1f5fe', color: '#01579b' }}>
      <strong>Note:</strong> Custom orders might see extended processing timelines. Regional courier delays are handled proactively by our support.
    </div>
  </section>
);

const Refund = () => (
  <section className="policy-section-animation" style={{ lineHeight: '1.8', fontSize: '0.95rem', color: '#4a5568' }}>
    <div className="d-flex align-items-center gap-3 mb-4">
      <div className="rounded-circle bg-danger bg-opacity-10 p-3 text-danger d-flex align-items-center justify-content-center" style={{ width: '56px', height: '56px' }}>
        <FaUndoAlt size={24} />
      </div>
      <div>
        <h4 className="fw-bold mb-0 text-dark">Return & Refund Policy</h4>
        <p className="text-muted small mb-0">Last updated: July 2026</p>
      </div>
    </div>
    
    <p className="text-secondary mb-4">
      We want you to be fully satisfied. If a custom print product is defective or damaged, we offer hassle-free returns.
    </p>

    <div className="row g-4 mb-4">
      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">Return Conditions:</h6>
          <ul className="list-unstyled d-flex flex-column gap-2 mb-0 small text-muted">
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Item must be unused and in original tag/packaging.</li>
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Defective reports should be raised within 7 days of delivery.</li>
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Return pickup is scheduled at no extra charge for verified defects.</li>
          </ul>
        </div>
      </div>

      <div className="col-12 col-md-6">
        <div className="card h-100 border-0 p-3 rounded-3 bg-light">
          <h6 className="fw-bold text-dark mb-2">Refund Processing:</h6>
          <ul className="list-unstyled d-flex flex-column gap-2 mb-0 small text-muted">
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Checked and approved within 2 days of warehouse receipt.</li>
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Refund credits posted to original payment mode in 5-7 business days.</li>
            <li className="d-flex gap-2"><FaCheckCircle className="text-danger mt-1" size={14} /> Original shipping costs refunded for verified production issues.</li>
          </ul>
        </div>
      </div>
    </div>
  </section>
);

export default PolicyPage;
