import React from "react";
import { Nav } from "react-bootstrap";
import { Routes, Route, Link, useLocation, Navigate } from "react-router-dom";
import "./Policy.css";
import PageNotFound from "../pageNotFound/PageNotFound";

const PolicyPage = () => {
  const location = useLocation();

const tabs = [
    { path: "/policy/terms", label: "Terms & Conditions" },
    { path: "/policy/privacy", label: "Privacy Policy" },
    { path: "/policy/shipping", label: "Shipping Policy" },
    { path: "/policy/refund", label: "Return & Refund Policy" },
  ];

  return (
    <div className="policy-page container-fluid mx-0 px-0 py-3 py-lg-5 bg-light">
      <h2 className="fw-bold text-center mb-4 text-dark">Our Policies</h2>

      {/* Tabs */}
      <Nav variant="tabs" className="justify-content-start justify-content-md-center mb-4 border-bottom-0 flex-nowrap overflow-auto" style={{ whiteSpace: 'nowrap' }}>
        {tabs.map((tab) => (
          <Nav.Item key={tab.path} className="">
            <Nav.Link
              as={Link}
              to={tab.path}
              className={`policy-tab px-3 px-md-4 py-3 fw-semibold ${location.pathname === tab.path ? "active-tab border-bottom border-3 border-primary text-primary" : "text-secondary"
                } text-decoration-none bg-transparent`}
            >
              {tab.label}
            </Nav.Link>
          </Nav.Item>
        ))}
      </Nav>

      {/* Policy Content */}
      <div className="policy-content mx-auto p-4 p-md-5 rounded-4 shadow-sm bg-white" style={{ maxWidth: '1000px' }}>
        <Routes>
          <Route path="/" element={<Navigate to="terms" replace />} />
          <Route path="terms" element={<Terms />} />
          <Route path="privacy" element={<Privacy />} />
          <Route path="shipping" element={<Shipping />} />
          <Route path="refund" element={<Refund />} />
          <Route path="*" element={<PageNotFound />} />
        </Routes>
      </div>
    </div>
  );
};

export default PolicyPage;

/* ---------- INDIVIDUAL POLICY COMPONENTS ---------- */

const Terms = () => (
  <section className="text-muted" style={{ lineHeight: '1.9', fontSize: '1.05rem' }}>
    <h3 className="fw-bold mb-4 text-dark" style={{ letterSpacing: '-0.5px' }}>Terms & Conditions</h3>
    
    <div className="alert alert-warning border-0 rounded-3 mb-5 shadow-sm" role="alert">
      <strong className="text-dark">Disclaimer:</strong> In case of any discrepancy or difference, the English version will take precedence over the translation.
    </div>
    
    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">1. Electronic Record</h5>
      <p>
        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
      </p>
    </div>

    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">2. Rule of Publishing</h5>
      <p>
        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").
      </p>
    </div>

    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">3. Ownership</h5>
      <p>
        The Platform is owned by <strong className="text-dark">Printmont Corporation Pvt. Ltd.</strong>, a company incorporated under the Companies Act, 1956 with its registered office at 3398, Bagichi Acchi ji, Bara Hindu Rao, Near Filmistan Cinema, New Delhi, India - 110006 (hereinafter referred to as "Printmont").
      </p>
    </div>

    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">4. Binding Obligations</h5>
      <p>
        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Printmont Corporation Pvt. Ltd. and these terms and conditions including the policies constitute Your binding obligations, with Printmont.
      </p>
    </div>

    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">5. Minor Transactions</h5>
      <p>
        As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Printmont reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Printmont's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.
      </p>
    </div>

    <div className="mb-5">
      <h5 className="fw-bold text-dark mb-3">6. Definitions</h5>
      <p>
        For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Printmont allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Printmont Corporation Pvt. Ltd.
      </p>
    </div>

    <div className="bg-light p-4 rounded-3 border">
      <p className="mb-0 text-dark fw-semibold" style={{ fontSize: '0.95rem' }}>
        ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Printmont Policies (including but not limited to Privacy Policy available at Privacy) as amended from time to time.
      </p>
    </div>
  </section>
);

const Privacy = () => (
  <section>
    <h4 className="fw-bold mb-3">Privacy Policy</h4>
    <p>
      Your privacy is important to us. We collect personal information only to
      enhance your experience and provide better services. All data is handled
      securely and will not be shared with third parties without consent.
    </p>
    <ul>
      <li>We use cookies for personalization and analytics.</li>
      <li>Users can request deletion of personal data.</li>
      <li>Data is stored securely using encryption standards.</li>
    </ul>
  </section>
);

const Shipping = () => (
  <section>
    <h4 className="fw-bold mb-3">Shipping Policy</h4>
    <p>
      We strive to deliver your orders quickly and safely. Our standard
      processing time is 2-3 business days. Delivery timelines vary based on
      location.
    </p>
    <ul>
      <li>Orders are shipped within 2-3 business days after confirmation.</li>
      <li>Tracking information will be shared via email.</li>
      <li>Delays due to weather or customs are beyond our control.</li>
    </ul>
  </section>
);

const Refund = () => (
  <section>
    <h4 className="fw-bold mb-3">Return & Refund Policy</h4>
    <p>
      We want you to be fully satisfied with your purchase. If you are not
      happy with your order, you may return eligible items within 7 days of
      delivery.
    </p>
    <ul>
      <li>Items must be unused and in original packaging.</li>
      <li>Refunds are processed within 5-7 business days after approval.</li>
      <li>Shipping costs are non-refundable unless due to our error.</li>
    </ul>
  </section>
);
